version: "2"
services:
  pg:
    image: postgres:latest
  ringer:
    build:
      context: .
      args:
        RUST_TOOLCHAIN: nightly
    links:
      - pg
    environment:
      - DATABASE_URL=postgres://postgres:@pg/ringer
      - MATTERMOST_URL=https://matter.oneiros.cc
      - MATTERMOST_HOOK=dyrhpx1dejy5ujctzn6tmjstio
    command: cargo test