version: "2"
services:
  pg:
    image: postgres:latest
  ringer:
    build:
      context: .
      args:
        RUST_TOOLCHAIN: nightly
    links:
      - pg
    environment:
      - $DB_URL=postgres://postgres:@192.168.99.100/ringer
    command: cargo test